RobotConfig:
  robot_ip: "192.168.1.29"  # left
  # robot_ip: "192.168.1.195" # right
  gripper_type: 2
  start_joints: [0, 0, 0, -3.1415927, 1.570796, -1.570796]
  start_tcp_pose: [350, 0, 250, -1.570796, 0, -1.570796]

TeleoperatorConfig:
  serial_number: "250801DR48FP26001318" # left
  # serial_number: "250801DR48FP26001295" # right
  use_vive_tracker: True
  vive_tracker_id: "LHR-555DC7BF"  # left
  # vive_tracker_id: "LHR-2425BAD3"  # right
  use_gripper: True
  tracker_to_robot_eef: [0, 0, 0, 0, 0, -1.570796] # left
  # tracker_to_robot_eef: [0, 0, 0, 0, 0, 1.570796] # right
  robot_base_pose: [350, 0, 250, -1.570796, 0, -1.570796]
